/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "surface-container": "#f1edec",
        "surface-variant": "#e5e2e1",
        "primary-container": "#faf9f6",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#464745",
        "on-surface-variant": "#444844",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#ebe7e6",
        "primary-fixed-dim": "#c7c6c4",
        "surface-dim": "#ddd9d8",
        "on-secondary-container": "#636262",
        "on-primary-fixed": "#1a1c1a",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#fcf8f7",
        "tertiary-fixed-dim": "#ebc23e",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        "on-surface": "#1c1b1b",
        tertiary: "#735c00",
        "on-primary-container": "#727270",
        outline: "#757874",
        "error-container": "#ffdad6",
        "primary-fixed": "#e3e2e0",
        "outline-variant": "#c5c7c3",
        "on-secondary-fixed-variant": "#474746",
        secondary: "#5f5e5e",
        "on-primary": "#ffffff",
        "inverse-surface": "#313030",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-tint": "#5e5f5d",
        surface: "#fcf8f7",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c7c6c4",
        "on-error-container": "#93000a",
        background: "#fcf8f7",
        primary: "#5e5f5d",
        "on-tertiary-fixed-variant": "#574500",
        "inverse-on-surface": "#f4f0ef",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#fff8ef",
        "surface-container-low": "#f7f3f2",
        "on-tertiary-container": "#8b6f00",
        "tertiary-fixed": "#ffe087",
        "accent-mint": "#A7F3D0",
        "accent-sky": "#BAE6FD",
        "accent-lavender": "#E9D5FF",
        "accent-apricot": "#FED7AA",
        "brand-yellow": "#FFD54F",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xl: "64px",
        md: "24px",
        "margin-desktop": "48px",
        sm: "16px",
        "margin-mobile": "16px",
        gutter: "24px",
        lg: "40px",
        xs: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "label-bold": ["Quicksand", "sans-serif"],
        "body-lg": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
        "label-sm": ["Quicksand", "sans-serif"],
        "headline-xl": ["Quicksand", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};